# Generated by Django 4.0.4 on 2022-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvCert',
            fields=[
                ('display_order', models.IntegerField(verbose_name='Display order')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('icon_tag', models.CharField(blank=True, max_length=99, verbose_name='Icon')),
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Title')),
                ('title_extra', models.CharField(blank=True, max_length=200, verbose_name='Title Extra[Superscript]')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='Organizer/Issuer')),
                ('courses', models.TextField(blank=True, max_length=65535, verbose_name='Courses sep by vert')),
                ('details', models.CharField(blank=True, max_length=999, verbose_name='Extra Details')),
                ('imgname', models.CharField(blank=True, max_length=99, verbose_name='Certificate filename')),
                ('verify_link', models.CharField(blank=True, max_length=999, verbose_name='Verification url')),
            ],
        ),
        migrations.CreateModel(
            name='CvExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(verbose_name='Display order')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('row1', models.CharField(max_length=999, verbose_name='Title Row')),
                ('row2', models.CharField(blank=True, max_length=999, verbose_name='Row 2')),
                ('row3', models.CharField(blank=True, max_length=999, verbose_name='Detail row sep by vert')),
                ('row4', models.CharField(blank=True, max_length=999, verbose_name='Extra row4')),
                ('row5', models.CharField(blank=True, max_length=999, verbose_name='Extra row5')),
            ],
        ),
    ]
