# Generated by Django 4.0.4 on 2022-06-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmRegistry',
            fields=[
                ('vmid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Assigned VMID')),
                ('project', models.CharField(max_length=99, verbose_name='Project')),
                ('role', models.CharField(max_length=20, verbose_name='Usage Role')),
                ('provider', models.CharField(max_length=10, verbose_name='Cloud providor')),
                ('zone', models.CharField(max_length=20, verbose_name='Zone')),
                ('resource', models.CharField(blank=True, max_length=99, verbose_name='Resource Id')),
                ('batchnum', models.IntegerField(verbose_name='BatchN')),
            ],
        ),
        migrations.CreateModel(
            name='VmTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.CharField(max_length=20, verbose_name='Assigned VMID')),
                ('event', models.CharField(max_length=1023, verbose_name='Event')),
                ('info', models.CharField(blank=True, max_length=9999, verbose_name='Information')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YCrawlConfig',
            fields=[
                ('name', models.CharField(max_length=1023, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, max_length=65535, verbose_name='Value (str / json as str)')),
            ],
        ),
        migrations.CreateModel(
            name='VmActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=1023, verbose_name='Event description')),
                ('info', models.CharField(blank=True, max_length=9999, verbose_name='Information')),
                ('result', models.CharField(blank=True, max_length=9999, verbose_name='Action Output')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('vmids', models.ManyToManyField(to='ycrawl.vmregistry')),
            ],
        ),
        migrations.CreateModel(
            name='BatchJobList',
            fields=[
                ('jobid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('weburl', models.CharField(max_length=65535)),
                ('completion', models.BooleanField(default=False, verbose_name='Completed?')),
                ('note', models.CharField(blank=True, max_length=1023)),
                ('vmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ycrawl.vmregistry')),
            ],
        ),
    ]
