# Generated by Django 4.0.3 on 2022-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycrawl', '0002_remove_vmtrail_id_remove_vmtrail_vm_vmtrail_vmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtrail',
            name='id',
            field=models.BigAutoField(auto_created=True, default=999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vmtrail',
            name='vmid',
            field=models.CharField(max_length=20, verbose_name='Assigned VMID'),
        ),
    ]
