# Generated by Django 4.0.3 on 2022-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycrawl', '0004_vmactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmActionShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=1023, verbose_name='Event description')),
                ('info', models.CharField(blank=True, max_length=9999, verbose_name='Information')),
                ('project', models.CharField(blank=True, max_length=99, verbose_name='Project Filter')),
                ('role', models.CharField(blank=True, max_length=20, verbose_name='Role Filter')),
                ('provider', models.CharField(blank=True, max_length=10, verbose_name='Provider Filter')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
