# Generated by Django 4.0.4 on 2022-05-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ycrawl', '0009_joblist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobList',
            new_name='BatchJobList',
        ),
    ]
