# Generated by Django 4.0.4 on 2022-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(upload_to='vision/')),
                ('userdesc', models.CharField(blank=True, max_length=1023, verbose_name='User Description')),
                ('model', models.CharField(max_length=100, verbose_name='Vision Model Selection')),
                ('outjson', models.TextField(blank=True, max_length=65535, verbose_name='Value (json as str)')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
