# Generated by Django 4.0.4 on 2022-04-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiondb',
            old_name='model',
            new_name='aimodel',
        ),
    ]
