# Generated by Django 4.0.4 on 2022-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_rename_model_visiondb_aimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiondb',
            name='aimodel',
            field=models.CharField(choices=[('Web API', (('AZ', 'Azure Congnitive'), ('GCP', 'Google Cloud Vision'))), ('Local', (('mn', 'Mobilenet'), ('yolov3', 'YOLO-416'), ('yolov3-tiny', 'YOLO-tiny'))), ('Special-3-step', (('husky', 'Haar + EfficientNet + MobileNetV3 (slow)'),))], max_length=100, verbose_name='Select a vision model'),
        ),
        migrations.AlterField(
            model_name='visiondb',
            name='userimage',
            field=models.ImageField(upload_to='vision/', verbose_name='Upload a picture'),
        ),
    ]
