# Generated by Django 4.0.4 on 2022-05-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebTasks',
            fields=[
                ('task', models.IntegerField(primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(default=True, verbose_name='Active?')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='Task Group')),
                ('webaddress', models.CharField(max_length=9999, verbose_name='Web URL')),
                ('keyfield', models.CharField(max_length=9999, verbose_name='XPATH')),
                ('display', models.CharField(max_length=100, verbose_name='Display Text')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='WebReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=65535, verbose_name='Response')),
                ('status', models.CharField(max_length=1023, verbose_name='Status')),
                ('info', models.CharField(blank=True, max_length=255, verbose_name='Extra Info')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webreader.webtasks')),
            ],
        ),
    ]
