# Generated by Django 4.0.4 on 2022-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webreader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webreader',
            name='info',
            field=models.TextField(blank=True, max_length=1048576, verbose_name='Extra Info'),
        ),
        migrations.AlterField(
            model_name='webreader',
            name='response',
            field=models.TextField(max_length=1048576, verbose_name='Response'),
        ),
    ]
