# Generated by Django 4.0.4 on 2022-06-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webreader', '0002_alter_webreader_info_alter_webreader_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webreader',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
