# Generated by Django 4.0.4 on 2022-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webreader', '0004_markitdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1024, verbose_name='Description')),
                ('doc', models.FileField(upload_to='docs')),
            ],
        ),
    ]
