# Generated by Django 4.0.3 on 2022-03-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmRegistry',
            fields=[
                ('vmid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Assigned VMID')),
                ('project', models.CharField(max_length=99, verbose_name='Project')),
                ('zone', models.CharField(max_length=20, verbose_name='Zone')),
                ('resource', models.CharField(blank=True, max_length=99, verbose_name='Resource Id')),
                ('batchnum', models.IntegerField(verbose_name='BatchN')),
            ],
        ),
        migrations.CreateModel(
            name='VmTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=1023, verbose_name='Event description')),
                ('info', models.CharField(max_length=9999, verbose_name='Information')),
                ('logdt', models.DateTimeField(verbose_name='Timestamp of Event')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.vmregistry')),
            ],
        ),
    ]
