# Generated by Django 4.0.3 on 2022-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmregistry',
            name='provider',
            field=models.CharField(default='na', max_length=10, verbose_name='Cloud providor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmregistry',
            name='role',
            field=models.CharField(default=1, max_length=20, verbose_name='Usage Role'),
            preserve_default=False,
        ),
    ]
