# Generated by Django 4.0.4 on 2022-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(max_length=99, verbose_name='Target Audience')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='Service Provider')),
                ('text', models.CharField(max_length=20, verbose_name='Text')),
                ('richcontent', models.TextField(blank=True, max_length=65535, verbose_name='Rich Content')),
                ('response', models.TextField(blank=True, max_length=65535, verbose_name='Response')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
