# Generated by Django 4.0.4 on 2022-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerdata',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Text'),
        ),
    ]
