# Generated by Django 4.0.4 on 2022-05-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUrl',
            fields=[
                ('rawurl', models.CharField(max_length=1023, primary_key=True, serialize=False, verbose_name='Raw URL')),
                ('cleanurl', models.CharField(max_length=1023, verbose_name='Display URL')),
                ('menu1', models.IntegerField(verbose_name='MainNav Order')),
                ('menu2', models.IntegerField(verbose_name='SideNav Order')),
                ('desc1', models.CharField(blank=True, max_length=200, verbose_name='Desc-main')),
                ('desc2', models.CharField(blank=True, max_length=200, verbose_name='Desc-side')),
                ('icon', models.CharField(blank=True, max_length=200, verbose_name='Icon')),
            ],
        ),
    ]
