# Generated by Django 4.0.4 on 2022-05-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteurl',
            name='desc3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Desc-override'),
        ),
        migrations.AddField(
            model_name='siteurl',
            name='menu3',
            field=models.IntegerField(default=123456, verbose_name='ListNav Order'),
            preserve_default=False,
        ),
    ]
