# Generated by Django 4.0.4 on 2022-05-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_siteurl_desc3_siteurl_menu3'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteurl',
            name='style',
            field=models.CharField(blank=True, max_length=999, verbose_name='Styling'),
        ),
    ]
